### ISSUE TITLE
Update ABI version

### ISSUE THREAD

**Issue by Eduardogbg** [near/near-abi-client-rs#10]
This crate is very useful, however it's not working with the latest ABI versions. Are there plans to update it? Is it going to be deprecated? Are there any alternatives?

Thanks

**Comment by Eduardogbg** [comment]
I've been working on a patch for this, but I'm confused about how `near_sdk::Promise`s are supposed to be generated, and I can't find examples of this from previous versions. I guess there's no way to statically determine the return type for a contract method that returns a promise, and the only solution would be to let it be `serde_json::Value`, is that correct?

**Comment by itegulov** [comment]
> I'm confused about how `near_sdk::Promise`s are supposed to be generated, and I can't find examples of this from previous versions. I guess there's no way to statically determine the return type for a contract method that returns a promise

Yeah, unfortunately, near-sdk-rs promises are untyped and therefore we cannot deduce a meaningful type for methods returning promises. We have been exploring how to add typed promises though (see https://github.com/near/near-sdk-rs/pull/803).

> the only solution would be to let it be `serde_json::Value`, is that correct?

We represent `Promise`s as a `true` schema in the JSON Schema terms (meaning any value passes through validation). I would say it is fair to represent such values as `serde_json::Value`. This would be a separate issue, but feel free to take it on if you want!
